export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const REQUEST_IMAGES_DATA_ERROR = 'REQUEST_IMAGES_DATA_ERROR';
export const REQUEST_IMAGES_DATA_RECEIVED = 'REQUEST_IMAGES_DATA_RECEIVED';
export const REQUEST_SET_TERM = 'REQUEST_SET_TERM';
